### ISSUE TITLE
Role

### ISSUE THREAD

**Issue by mhamiache** [signumsoftware/framework#115]
Hi,
I m trying to show or not to show thing depending if the user inside a role has read permission on some entity.
How can i do that?
For example my view of my account has a list of BonusEntity and i dont want everybody to see this:
<div class="panel-body">@Html.SearchControl(new FindOptions(typeof (BonusEntity), "Entity.Account", ac.Value), new Context(ac, "BonusEntity"))</div>

Thanks

**Comment by olmobrutall** [comment]
with 

```CSHTML
@if(Finder.IsFindable(typeof (BonusEntity))){

}
```

And using the authorization system. If you have just a SearchControl is automatic, but if you have a Tab or Group you need to use it. 

BTW you can also find us in https://gitter.im/signumsoftware/framework
