### ISSUE TITLE
webpack-assets.json file not found

### ISSUE THREAD

**Issue by otamimi** [signumsoftware/framework#135]
the solution builds successfully but an error happens when loading the home page

`Could not find file 'C:\Users\###\Documents\Visual Studio 2015\Projects\exams\exams.React\dist\webpack-assets.json'.`

`Line 4:  @{
Line 5:  
Line 6:      string json = File.ReadAllText(Path.Combine(Server.MapPath("~/dist/"), "webpack-assets.json"));
Line 7:      var webpackAssets = JObject.Parse(json).Properties()
Line 8:          .ToDictionary(a => a.Name, a => Url.Content("~/dist/" + (string)a.Value["js"]));`

> Source File: C:\Users\#####\Documents\Visual Studio 2015\Projects\exams\exams.React\Views\Home\Index.cshtml    Line: 6

**Comment by otamimi** [comment]
i ran "webpack -d" **again** and it solved the problem.

**Comment by olmobrutall** [comment]
Yes, you have to run webpack in order to get it. 

https://github.com/signumsoftware/framework/wiki/Signum-React 

At the end explains how to add a [webpack] button next to VS play button.

I recommend you to use "webpack --progress -w"
