### ISSUE TITLE
What happend to EntityCodeGenerator.CleanDiffTables?

### ISSUE THREAD

**Issue by rvlieshout** [signumsoftware/framework#147]
Following the steps to use the signum framework with a legacy database, I failed to call
`base.CleanDiffTables(tables);` (I could not find any method on the base class with any similar name.

**Comment by olmobrutall** [comment]
Hi, welcome to the community :).

I recommend you to play a little bit with southwind first before you get into legacy databases. Autogenerating an application requires some faimiliarity with the framework concepts. 

About CleanDiffTables, now is called GetTables. 

In your override you can call the base, get the results, clean them and return them.
