### ISSUE TITLE
dynamic userinterface

### ISSUE THREAD

**Issue by mdissel** [signumsoftware/framework#175]
I'm evaluating this framework and was wondering if it's possible to modify the default userinterface using an extension module.

customer request:
client entity userinterface should contain an extra field on the second line 

implementation:
create an extension module for this specific customer that will create an additional field / entity and modify the default client entity userinterface to add this field  on the second line.

Thanks

**Comment by olmobrutall** [comment]
Hi @mdissel,

Nice that you're evaluating the framework, it won't disappoint ;)
 
It's definitely possible to add new fields / customize the UI for entities provided by Framework / Extensions. This is what mixins are for: 

http://www.signumsoftware.com/en/Framework (mixins)
http://www.signumsoftware.com/Documentation/framework/master/Signum.Entities/Mixin.md

For customizing the UI you have an example in the reference application: 

https://github.com/signumsoftware/southwind/blob/master/Southwind.React/App/Southwind/SouthwindClient.tsx

Look for overrideView. 

Hope it helps

**Comment by mdissel** [comment]
Ok, found the code:

```
    Navigator.getSettings(UserEntity)!.overrideView((rep) => {
        rep.insertAfter(u => u.role,
            <ValueLine ctx={rep.ctx.subCtx(u => getMixin(u, UserEmployeeMixin).allowLogin, { labelColumns: { sm: 3 } }) }/>,
            <EntityLine ctx={rep.ctx.subCtx(u => getMixin(u, UserEmployeeMixin).employee, { labelColumns: { sm: 3 } }) }/>)
    });
```

But how can i add this dynamically from an external module?

**Comment by olmobrutall** [comment]
You can write this code anywhere, it changes an internal global dictionary. 

If by dynamically you mean that the end-user will do it, then there is an extension for it: DynamicView

https://github.com/signumsoftware/extensions/blob/master/Signum.React.Extensions/Dynamic/DynamicViewClient.tsx

**Comment by mdissel** [comment]
But in the sample the default view is defined in React/tsx. Can you override this view from c# code during the initial bootstrapping of the application?

**Comment by olmobrutall** [comment]
No, you have to override it from React, during the initial bootstrapping

**Comment by olmobrutall** [comment]
Of course you could call a Rest service from React to C# to drive the process from the C#/Database side. This is more or less what DynamicViewClient does.

**Comment by mdissel** [comment]
You know what the next question will be... Is there a sample and if not...

**Comment by olmobrutall** [comment]
Maybe I can get sample done this weekend, bur no guarantees

**Comment by olmobrutall** [comment]
I tried to adapt Southwind to add Dynamic entities and Views, but didn't manage to make it work. Some issues with roslyn/CodeDom not being copied to the bin directory. 

I need to check with @MehdyKarimpour to see how is his configuration, since he is the one using it.

**Comment by olmobrutall** [comment]
Hi @mdissel, 

Thanks to @MehdyKarimpour  for fixing the bin probkem, I just added a new branch in Southwind that enables all the Dynamic modules (there are a few) in Southwind. 

https://github.com/signumsoftware/southwind/tree/Dynamic

How to test it: 

* Omnibox: DynamicType
* Create a new type (i.e "Factory") and save
* Omnibox: !DynamicPanel
* Follow the steps (Compile/Restart/Create and execute Migration)
* Omnibox: Factory
* Create new factories

Its a complicated module, and probably there will be issues. 

Tell me if you have any problem

**Comment by olmobrutall** [comment]
Any progress? Can I close the issue?
