### ISSUE TITLE
Rare SQL hangs (timeouts) in conections in (complex?) queries 

### ISSUE THREAD

**Issue by modma** [signumsoftware/framework#182]
Hi, another problem detected using the app, is a query than executes well the first time, in another scenarios causes a timeout, the rare question is the frameworks stops in a simple query (copy this query and execute it in the managment studio, and works fast), and this is not possible...
any idea? you need more debug information?

![error raro timeout](https://cloud.githubusercontent.com/assets/16271691/24394453/5a17e416-139c-11e7-8a4f-928e0ebe7374.gif)

Principal: 
```
new ReciboMotorEntity((PrimaryKey?)(rm.ID))
{
     id = (PrimaryKey?)(rm.ID),
     ticks = rm.Ticks,
     toStr = rm.ToStr,
     <AgrupacionInformeEstadistico>k__BackingField = (new InformeEstadisticoContableEntity((PrimaryKey?)(rm.AgrupacionInformeEstadisticoID))
    {
     
    }
    ).ToLite(),
     <TipoPoliza>k__BackingField = Convert(Convert(rm.TipoPolizaID)),
     <RetenidaAgruapcionEmision>k__BackingField = rm.RetenidaAgruapcionEmision,
     <Extorno>k__BackingField = rm.Extorno,
     <PeriodoRenovacion>k__BackingField = (new PeriodoRenovacionEntity((PrimaryKey?)(rm.PeriodoRenovacionID))
    {
     
    }
    ).ToLite(),
     <Tarifa>k__BackingField = (new TarifaMotorEntity((PrimaryKey?)(rm.TarifaID))
    {
     
    }
    ).ToLite(),
     <Beneficiario>k__BackingField = new FiscalEntity((PrimaryKey?)(rm.BeneficiarioID))
    {
     
    }
    ,
     fechaInicio = rm.FechaInicio,
     fechaFinal = rm.FechaFinal,
     <FechaRecuperacion>k__BackingField = rm.FechaRecuperacion,
     <NumeroRecibo>k__BackingField = rm.NumeroRecibo,
     entry = new EntryEntity((PrimaryKey?)(rm.EntryID))
    {
     
    }
    ,
     <CodigoColaboracion>k__BackingField = new SalesPartnerCodeEntity((PrimaryKey?)(rm.CodigoColaboracionID))
    {
     
    }
    ,
     <Desglose>k__BackingField = (new DesgloseMotorEntity((PrimaryKey?)(rm.DesgloseID))
    {
     
    }
    ).ToLite(),
     <Compensador>k__BackingField = new ReciboMotorEntity((PrimaryKey?)(rm.CompensadorID))
    {
     
    }
    ,
     <FechaCompensacion>k__BackingField = rm.FechaCompensacion,
     <Concepto>k__BackingField = rm.Concepto,
     <EsCompensador>k__BackingField = rm.EsCompensador,
     <FechaActivacion>k__BackingField = rm.FechaActivacion,
     <AgrupacionLq>k__BackingField = (new ReciboMotorAgrupacionEntity((PrimaryKey?)(rm.AgrupacionLqID))
    {
     
    }
    ).ToLite(),
     <AgrupacionLqMultitarificadores>k__BackingField = (new AgrupacionRecibosArpemEntity((PrimaryKey?)(rm.AgrupacionLqMultitarificadoresID))
    {
     
    }
    ).ToLite(),
     <RecaudaColaborador>k__BackingField = rm.RecaudaColaborador
}
.Mixin(new CorruptMixin
{    <Corrupt>k__BackingField = rm.Corrupt
})
.Mixin(new IsolationMixin
{    <Isolation>k__BackingField = (new IsolationEntity((PrimaryKey?)(rm.IsolationID))
    {
     
    }
    ).ToLite()
})
```

**Comment by olmobrutall** [comment]
Probably is related to a new database where Snapshot Isolation is not active. 
Try synchronizing.

**Comment by modma** [comment]
yes the sincronization is correctly, the problem resides in `SqlDependency` in the 3rd call the reader no executes, if remmarks this, it works, i´ll try to test with sqlexpress 2016, my corporation uses 2008, i think that no supports very weel in this version, I'll try tomorrow...

**Comment by modma** [comment]
ok, i dedicated a lot of time investigating this: 
![lockerr1](https://cloud.githubusercontent.com/assets/16271691/24503484/9a04d054-1552-11e7-9369-39509a612830.png)

I destroy the recursivity of `CacheTable.LoadAll` to optimize & check who Made the problem: a `MListCache` of `Lite`??
![lockerr3](https://cloud.githubusercontent.com/assets/16271691/24503559/ddc46282-1552-11e7-85f6-ec4a81f6091f.png)

`SqlDependency` fails at this, i remove manualy this entry of the list, the test method works a expected, my first thought was that it could be a problem of duplicity with the previous one, but removing the previous one from that of the list, I discovered that it did not :(
This issue is caused by `Business.BankAccountEntity.Holders` posibily we may not have the same code in the same entity (versions)...

I explain: my envioremnt uses `CrearEntorno`, this is a Test Method to do in my case a insert with isolation in management in Logic Tests;
this is no a problem caused by no execute doing the "acbd" in "Load" Console utility, now i use the user "sa" on MSSQL2016 Express to discard old versions & permissions, any idea? thanks

**Comment by olmobrutall** [comment]
Sorry but I still don't understand the problem. In the first screenshot I'm missing an stacktrace. 

Still I would bet for snapshot isoplation not being enabled. Can you manually check if it's enabled?

**Comment by modma** [comment]
Yes snapshot isolation is correctly enabled, i renabled some times to discard, and the app works in some calls using the 'SqlDependency', je, the stack trace is a chaos, but i found now the problem `SqlDependency` is exhaust in more calls in the recursive LoadAll, 

![lockerr4](https://cloud.githubusercontent.com/assets/16271691/24511008/16d8b470-156b-11e7-9647-9ba862b9bca3.png)
Good Notices, i found a way to fix my problem. the fix is rehuse the SqlDependency, now i see a good thing, forgotten calls (yes) is recived to the method fired... :)

![lockerr5](https://cloud.githubusercontent.com/assets/16271691/24511111/5d3738a6-156b-11e7-9299-76d5d7e87a88.png)

**Comment by modma** [comment]
Hi, I made a video, you can see in it the problem easy
https://1drv.ms/v/s!AlQgq_6rDEMGhMcjiUWt3LKqE5-9Lw

**Comment by olmobrutall** [comment]
Hi modma, 

I've been looking the video and there are two things that surprise me, BankAccountEntity looks like fully cached, with no condition. Does that make sense? Won't it be invalidated with every new customer? Maybe semi caching it is better. 

I can imagine that the test is in the process of creating a BankAccount in one transaction and loading all of them in another, creating deadlock. 

If this doesn't help you'll need to contact Signum Spain, since it requires a knowledge of the domain that I don't have anymore. 

Regards

**Comment by modma** [comment]
in teory the problem is caused by `Business.BankAccountEntity.Holders`:
```
namespace Business.Entities.Accounting
{
    [Serializable, EntityKind(EntityKind.Shared, EntityData.Transactional)]
    public class BankAccountEntity : LockableEntity 
    {
...
        [NotNullable, NotifyCollectionChanged]
        public MList<Lite<FiscalEntity>> Holders { get; set; } = new MList<Lite<FiscalEntity>>();
...
    }
}
```
I don't undertand why this simple query (_BankAccountHolder_  table) stops the `SqlDependency`, maybe the `Mlist of Lite` is no a good idea, but this code is migrated and in the old version, Adrian certifiedme that works ok in the old test framework...
Ok, how try modify the cache of this entity???? thanks

PD: A separate issue, keep in mind that `SqlDependency` objects are never deleted/disposed events are not unregistered (and in my debugging I see that the stack is filled with more than 300 ghost services in the operation (this object no disapperas when the comand disposes) I'm performing test); It seems that the application even works more efficiently with the modification when reusing it, consider treating this situation that I have found

**Comment by olmobrutall** [comment]
@modma  

> keep in mind that SqlDependency objects are never deleted/disposed events are not unregistered

I'm not aware of SqlDependency events needing to be disposed. They are triggered just once, so you should have one alive event per table only

**Comment by modma** [comment]
Okay, I'll keep that in mind; I close the topic because for this singular case a small fix has been made, thanks
