### ISSUE TITLE
Closing a new empty entity in the UI fire a prompt for un-saved changes

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#192]
The state of the entity should be checked, if isNew = true and none of the fields was updated, the prompt should not be appearing.

Thanks
Avi

**Comment by olmobrutall** [comment]
Hi Avi, 

The implications will be that an entity could be new but not modified. It's an interesting concept but will be cool that this behaviour could also happen for entities constructed from, or with special constrictors. 

Also c# entities should behave similarly to keep consistency. 

I'll consider to make the change and every annoying "save changes?" will serve me as a reminder. 

If somebody wants to try to make a PR, I can help him.

**Comment by olmobrutall** [comment]
Fixed in https://github.com/signumsoftware/framework/pull/275 
Thanks!
