### ISSUE TITLE
Importing the exprted xml menu.

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#241]
I have export my menu, and I want to import it from code.  
How would I provide the second parameter for the method: `FromXml()`  
Thanks
 ```
 using (AuthLogic.UnsafeUserSession("Super"))
 {
    ToolbarEntity en = new ToolbarEntity();
    en.FromXml(XElement.Load(AppDomain.CurrentDomain.BaseDirectory + "/ToolbarEntity.xml"));
    en.Save();
 }
```

**Comment by olmobrutall** [comment]
In Omnibox try !ImportUserAssets, same UI for dashboard, user charts, user queries and toolbars

**Comment by avifatal** [comment]
I want to import from code...

**Comment by olmobrutall** [comment]
Look at Southwind CSharp migrations
