### ISSUE TITLE
Where is the export tool bar to xml?

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#248]
I just setup a new app.  
Can't find the toolbar export to xml button:   
![c7ecqqo 1](https://user-images.githubusercontent.com/12430740/33793187-7f282db8-dcbb-11e7-9d08-4f22b6f9a34a.png)

Thanks

**Comment by olmobrutall** [comment]
Hi Mehdy, 

It's a QuickLink: 
![image](https://user-images.githubusercontent.com/720953/33796297-9dfa23e6-dcf1-11e7-880b-3c4b3e0a3a5c.png)

And a contextual action:
![image](https://user-images.githubusercontent.com/720953/33796300-adf000c2-dcf1-11e7-866b-6810344fb1f8.png)
