### ISSUE TITLE
Bug Report code generation.

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#274]
Hi,

![image](https://user-images.githubusercontent.com/12430740/39559632-57a615c8-4ea0-11e8-876f-1c69cb57bf64.png)
When trying to generate entity from database tables.

Maybe its related to the .net core code mix that you have now?

Thanks

**Comment by olmobrutall** [comment]
Currently Signum does not support multi-column Primary Keys. This in itself is not a problem, but typically is combined with columns that are at the same time PKs and FKs, and for which you don't do an UPDATE just INSERT / DELETE. 

The tutorial https://github.com/signumsoftware/framework/blob/master/Signum.Engine/CodeGeneration/LegacyDatabase.AdventureWorks.md shows how to handle this case. Basically: 

1. Override GetTables to pretend that there is a simple PK. 
2. Generate entities. 
3. Synchronize and he will create a new table with a simple PK and move the data. 

Tell me if you have any problems.
