### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by olmobrutall** [signumsoftware/framework#322]
Hi everybody,

In order to avoid distrust from companies using Signum Framework, Signum Extensions or Southwind, I would like to change the Software Licence from LGPL to MIT. 

* **LGPL:** https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3) It's more complicated to understand, and is used by few libraries https://en.wikipedia.org/wiki/Category:Software_using_the_LGPL_license

* **MIT:** https://tldrlegal.com/license/mit-license It's a simple: do what you want but we're not libable if it crashes. It's used by most of the libraries like .Net Core, React, Angular, jQuery, https://en.wikipedia.org/wiki/Category:Software_using_the_MIT_license

While I'm the main maintainer of the framework, there are contributions from many different people and I would like to be sure that a big majority agrees with the change. It doesn't have to be a 100% agreement, but we would need to remove the code from the ones who disagree. 

@olmobrutall, @antonioh-duplicate , @MehdyKarimpour, @AlejandroCano, @mapacheL, @JesusFrancesGarcia / @caltane , @adrianFarinaPiera, @ze-german, @aengin, @KonstantinLukaschenko,@ghockx1p, @sschoensee, @rondoo, @mindriven, @avifatal, @sschoensee could you state your aggreement with a 👍 MIT reply.

Thanks!

**Comment by olmobrutall** [comment]
👍 MIT

**Comment by ze-german** [comment]
👍 MIT

**Comment by juburchartz** [comment]
👌 MIT

**Comment by rondoo** [comment]
👍 MIT

**Comment by stammr** [comment]
👍 MIT

**Comment by sschoensee** [comment]
:+1: MIT

**Comment by antonioh** [comment]
👍 MIT

**Comment by AlejandroCano** [comment]
👍 MIT

**Comment by mapacheL** [comment]
👍 MIT

**Comment by KonstantinLukaschenko** [comment]
+1 MIT

**Comment by MehdyKarimpour** [comment]
MIT

**Comment by caltane** [comment]
👍 MIT

**Comment by aengin** [comment]
👍 MIT

**Comment by olmobrutall** [comment]
Thank you all for making it easy :) I'll change it now
