### ISSUE TITLE
EMail Message Create button is missing.

### ISSUE THREAD

**Issue by stammr** [signumsoftware/framework#402]
![EMAilMessage](https://user-images.githubusercontent.com/43534315/57450611-36e5cc00-725f-11e9-98c1-b5f674e47458.JPG)

The CreateNewMessage Button for MList<EmailTemplateMessageEmbedded> Messages is missing in the default EMailTemplate.tsx.

<EntityTabRepeater needs createAsLink value to reactivate it again. Is there a way to take control on the attribute createAsLink from outside ?

**Comment by olmobrutall** [comment]
Upsi.... is fixed not in cccf3ab144fad0ba78207ea6c93a68f5dc42ca3e
