### ISSUE TITLE
Setting up cache for master entities

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#42]
Hi,
In starter.cs I am adding the following function:

        private static void SetupCache(SchemaBuilder sb)
        {
            CacheLogic.CacheTable<CountryEntity>(sb);
            CacheLogic.CacheTable<LanguageEntity>(sb);
            CacheLogic.CacheTable<EmailEntity>(sb);
            CacheLogic.CacheTable<PixelEntity>(sb);
            CacheLogic.CacheTable<ChannelEntity>(sb);
            CacheLogic.CacheTable<BrandEntity>(sb);
        }

For some odd reason I am getting the following error: 

`
An exception of type 'System.ArgumentException' occurred in Signum.Utilities.dll but was not handled in user code
Additional information: CrmApp.Entities.ChannelEntity already registered
`

Can you please explain why is that?
Why didnt this happened to the first line?
Is this how you setup simple cache for EntityData.Master ?

Thanks

**Comment by avifatal** [comment]
Hi,
I found what it is. I read the source code and saw that when you cache an entity you already cache its related entities.
Since PixelEntity has reference to ChannelEntity, ChannelEntity is already cached as a child entity of PixelEntity. (one row before...).

In this case I dont think an exception is must to be thrown....
Thanks anyway.

**Comment by olmobrutall** [comment]
Oh!! Sorry for not answering. Yes it throws an exception of the main table is already registered an your line is unnecessary, but not for the recursive ones. 

Maybe doing nothing will be better, but then the developer will be surprised when he removes the line that the entity is still cached. 

One solution is too annoying and the other one too forgiving. Will be good to throw a warning :)
