### ISSUE TITLE
Omnibox does not take EntityData attribute into account

### ISSUE THREAD

**Issue by mnumeijer** [signumsoftware/framework#43]
When defining an entity as:

    [Serializable, EntityKind(EntityKind.System, EntityData.Transactional)]
    [Description("Logging")]
    public class MasterDataMessageLogging : Entity

and searching this entity by using the omnibox the results are default shown in ascending order of id instead of descending.

**Comment by olmobrutall** [comment]
You mean searching by text? I'll fix it :) 

Von meinem iPhone gesendet

**Comment by mnumeijer** [comment]
Not sure what you mean with your comment, but I have an entity defined as above, and a query as below:

                dqm.RegisterQuery(typeof(MasterDataMessageLogging), () =>
                    from q in Database.Query<MasterDataMessageLogging>()
                    select new 
                    {
                        Entity = q.ToLite(),
                        q.Target,
                        q.Identification,
                        q.Type,
                        q.DateTime,
                        q.Result,
                        q.Request,
                        q.Queue,
                        q.Duration,
                    });

The result is  
![image](https://cloud.githubusercontent.com/assets/907291/11657655/73efd6b4-9dbe-11e5-8c23-d0b56ee18dd8.png)

The default order is ascending id and EntityData.Transactional should order by id Descending, so in this case the latest logging entry should be the first row in the reslt.

**Comment by olmobrutall** [comment]
Strange, it should work. Can you take a look at Finder.SetDefaultOrder. This method is the one that should make it work.

**Comment by mnumeijer** [comment]
So this only works when I add Id in the query, in below code when Id is not part of the query column is null so the OrderOptions is not set...
 
               var column = description.Columns.SingleOrDefaultEx(c => c.Name == settings.DefaultOrderColumn);

                if (column != null)
                {
                    findOptions.OrderOptions.Add(new OrderOption{ Token = new ColumnToken(column, description.QueryName), ColumnName = column.Name, OrderType = orderType });
                }

**Comment by mnumeijer** [comment]
I think it would be better that, in case there is no OrderOptions, the default for Id should be taken whether or not this Id is present in the query.

**Comment by olmobrutall** [comment]
You could access the Id by parsing the token "Entity.Id" or "Entity." + DefaultOrderColumn. 

The UX will be a little bit strange, if the user decides to order by any other column he will be not able to easily go back to the old order, because is not shown. 

If this is ok for you, then is probably a better default behavior. 

Can you make a pull request?
