### ISSUE TITLE
Inheritance in Entities and code reuse

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#44]
Hi Olmo,
I have a usecase very similar to BillingInformationEntity and ShippingInformationEntity, How can 2 very similar entities can have inheritance between them and code reuse (query, ui and such).

Thanks
Avi

**Comment by olmobrutall** [comment]
Without more context I will go for using a common embedded entity, they could be exactly the same entity with the same UI just used in a bigger container (OrderEntity).


But I'll need to know the properties in this entities, if they are master or transactional, it's entity data, in what they are different, etc... To give you a better advice.
