### ISSUE TITLE
Chart button

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#47]
Chart button
 
![chart](https://cloud.githubusercontent.com/assets/13131520/11991350/0a6b289a-aa22-11e5-897b-43b4fc0b530d.png)

After clicking Chart button, I am getting an error with a message “No chart script loaded in the database”. How do I make it work?

**Comment by olmobrutall** [comment]
ChartScripts are database entities that can be loaded from Xml files. Just run the Load application-> load -> import export chart scripts. 

If you don't find the menu check of differences with     https://github.com/signumsoftware/southwind/blob/master/Southwind.Load/Program.cs

**Comment by roiez** [comment]
Than you Olmo, this resolves the issue.
