### ISSUE TITLE
Preserving user selections from previous page

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#48]
Preserving user selections from previous page, for example if I am at the page as illustrated by the image above, I would build some queries and then navigate to one of the rows details via the “View” link, then by clicking a browser back arrow, I want my queries to stay intact. I would also like to add a "Back" - return to previous page button to the inner pages.

**Comment by mapacheL** [comment]
My advice is to navigate rows in new tabs (CTRL + click instead of simple click on "View" link), so you allways preserve the state of your query.

**Comment by olmobrutall** [comment]
Also, if you update to the new version of the framework the entities are opened in pop-ups by default. 

This change of behavior, suggested by avi, has prove to be a good solution.

If you're still using mercurial, consider switching to git + git sub modules to make the framework update more straightforward. There are going to be much more update soon

**Comment by roiez** [comment]
upgraded to the new version - works like a charm, thank you
