### ISSUE TITLE
Display image

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#49]

**Comment by olmobrutall** [comment]
Signum framework does not provide any particular utility for images, it tries to stay arround database and entity stuff.  There are lots of possibilities

you can strore the images in file system (many) or the database (few)

you can use Base64 link (sync), a link to a controller or a link to a physical path (async). 

you can avoid the thumbnail and resize in client (high bandwith), calculate the thumbnail in memory in the server (high CPU and memory pressure) or store the already calculated thumbnail together with the image (best scalability with some aditional complexity). 

One thecnique that I´ve not used but is probably the best solution is to use the ability of some image formats to store the thumbnail embedded in the file: http://stackoverflow.com/questions/2808887/create-thumbnail-image 

Hope it helps.

**Comment by roiez** [comment]
Thank you, I have figured out the issue.



*From:* Olmo [mailto:notifications@github.com]
*Sent:* Monday, December 28, 2015 3:35 PM
*To:* signumsoftware/framework
*Cc:* roiez
*Subject:* Re: [framework] Display image (#49)



Signum framework does not provide any particular utility for images, it
tries to stay arround database and entity stuff. There are lots of
possibilities

you can strore the images in file system (many) or the database (few)

you can use Base64 link (sync), a link to a controller or a link to a
physical path (async).

you can avoid the thumbnail and resize in client (high bandwith), calculate
the thumbnail in memory in the server (high CPU and memory pressure) or
store the already calculated thumbnail together with the image (best
scalability with some aditional complexity).

One thecnique that I´ve not used but is probably the best solution is to
use the ability of some image formats to store the thumbnail embedded in
the file: http://stackoverflow.com/questions/2808887/create-thumbnail-image

Hope it helps.

—
Reply to this email directly or view it on GitHub
<https://github.com/signumsoftware/framework/issues/49#issuecomment-167570262>
.
