### ISSUE TITLE
Receiving emails via smpt

### ISSUE THREAD

**Issue by aleksei-krivoruchko** [signumsoftware/framework#491]
Hi @olmobrutall ,

we need to read emails from a mailbox and I see there is Pop3ConfigurationLogic which could do the job. Is there anything implemented to do the same via smpt?

**Comment by olmobrutall** [comment]
Hi @aleksei-krivoruchko, 

SMTP is the protocol for sending, POP3 is for receiving. 

Pop3ConfigurationLogic has the UI and DB infrastructure, but has an extension point to do the actual email reception. I think the recommended solution now is https://github.com/jstedfast/MailKit but maybe @AlejandroCano can confirm. 

About exchange, We have generalized SmtpConfiguration to be EmailSenderConfiguration, including exchange support. A similar change generalizing Pop3Configuration to include exchange as well will be a very welcome PR
