### ISSUE TITLE
Ability to disable prompt 'lose changes'

### ISSUE THREAD

**Issue by mharasimowiczcontrolexpert** [signumsoftware/framework#526]
Hello,

We would like to disable the 'lose changes' message box on the entity without changing the framework (or at least by changing the framework via a pull request after discussion) because this message is so notorious it's even blocking sending the form without accepting it. I assume it's might be an issue with our 'isNew' property, but disabling the message would be the preferred solution for us. 

We configure entity like that: 
![image](https://user-images.githubusercontent.com/11663497/149123647-30708e7c-b7ac-4321-97b9-df68078280fb.png)

The previous fork which we used just removed this line (mainline vs fork):
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/11663497/149124557-1ad718cc-c237-4918-935c-b210c960c238.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/11663497/149124569-ac7aae4a-91fb-4c0b-98e9-c5979fd97db2.png)

What's the best way to implement this?

Regards,
Michał

**Comment by olmobrutall** [comment]
I could imagine either:

* a static property disableLooseChangesPrompt in the FramePage function or a namespace FramePageOptions for a global option, default to false. 
* a new property disableLooseChangesPrompt in EntitySettings if the behaviour is problematic only for some particular entities. 

At the end of the day the best solution will be to dig into `GraphExplorer.propagateAll` and understand why the current behaviour is problematic. 

You can easily debug it by setting `window.exploreGraphDebugMode = true`

**Comment by mharasimowiczcontrolexpert** [comment]
Great, thank you for your response on such short notice.

We will try to debug the behavior or we will submit PR later as suggested above.

**Comment by mharasimowiczcontrolexpert** [comment]
Hello,
we managed

**Comment by olmobrutall** [comment]
Nice to hear that :)

**Comment by MehdyKarimpour** [comment]
Perfect 👌
