### ISSUE TITLE
Translation Problem in Dasboard Tab view

### ISSUE THREAD

**Issue by doganc** [signumsoftware/framework#539]
Hi, I have a translation problem in Dashboard TAB view,
I have some Dashboard items with user queries, 

![image](https://user-images.githubusercontent.com/8354931/152957227-bd4aa495-2f8e-4bb0-b39f-47ae61777ccc.png)

as it is seen, all Text translated perfectly to Turkish 

but the user login as a Turkish language, user steel see English text of Tab headers, but in tab, sections translated to Turkish,

How can I solve this problem?
Thanks for all

![image](https://user-images.githubusercontent.com/8354931/152957923-c73cd456-f9fe-4337-8efa-aa45e3798db0.png)

**Comment by olmobrutall** [comment]
I think the problem is in DashboardClient.tsx line 257

instead of 
 ```title: d.displayName,```

should be 
 ```title: translated(d, d => d.displayName),```

I'll push in master but you can make the change yourself if you don't want to update yet.

**Comment by doganc** [comment]
Hi Olmo,
Thanks for your help, it works
