### ISSUE TITLE
Problems with modal dialog

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#56]
Hi,
After upgrading the system, I saw this odd thing.
When you click the first time on "View" in the grid (certain grid), nothing happened. On the second time, it works and throw some JS errors like "Uncaught Error: 2 elements with id = 'nav_CreatedBy_hidden' found" 
if I understand the error, it found duplicated html elements, it is like the first window was opened, but not seen on the screen, than the second click on view, opens the modal again, and the other one is not closed.

So I did a little dom research, the forst click the modal dom shows up, but it is not on the screen.
the second click it is not destroyed and a new modal  coming in. this is the duplicate error.

The odd thing, it is happening only on one entity....

**Comment by olmobrutall** [comment]
In chrome tools check stop on caugh exceptions as well. Probably you'll find the error that is stopping the first modal to close.tell me if this brings some light.

**Comment by avifatal** [comment]
In the first click there is no error. it is just not showing up.
The error is coming in the second, when you have 3 modals with the field ids on the dom

**Comment by olmobrutall** [comment]
In Navigator.ts you have the methods for opening and closing modals. Try to look there why is no closing. If doesn't work I'll try to help you at some point today.
