### ISSUE TITLE
C# migration suggestion

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#57]
Hi,
When I run C# migration, I want to break it in to few migrations for "post migration tests".
The problem is that you cannot choose to run only the first migration, its all or nothing.

What do you think?
Avi

**Comment by olmobrutall** [comment]
Makes sense to use C# migrations when you have methods that:

* are relatively short (under 10 mins)
* have to be executed in some (lously) order before the deployment.
* we don't need to execute them again. 

It's just a kind of TODO list for deployment. 

If you need more flexibility in the order of execution, you can use the `Load` method that will create an interactive menu.

**Comment by avifatal** [comment]
So this area is actually under my control, right? I can actually do it myself?

**Comment by olmobrutall** [comment]
I mean the `Load` method in Program.cs. 

This file, belongs to your app, not to the framework or extensions, so is under your control.
