### ISSUE TITLE
How to use [CurrentEntity]  to filter current entity

### ISSUE THREAD

**Issue by ce-kkoziel** [signumsoftware/framework#574]
Dear @olmobrutall ,

Can you explain, or share some documentation, how to use [CurrentEntity] keyword while building custom user queries?

With regards,
Kozieł Karol

**Comment by doganc** [comment]
hi,
i've just use this expression my UserQuery like this,
I hope it's explain your question,

![CurrentUser](https://user-images.githubusercontent.com/8354931/186638931-4eaa1a68-a3e7-41dd-836f-2d80c3f1f5bf.gif)

**Comment by ce-kkoziel** [comment]
I have something like this. I have selected entity type and I want bind his Id property to filter value, but filter property is a string type. It is possible?

![obraz](https://user-images.githubusercontent.com/97600039/186647501-834e370f-66f6-4959-b098-d0919775106e.png)

**Comment by olmobrutall** [comment]
You could use `RestLog.QueryString.Any.Value`  `EqualsTo` `[CurrentEntity].Id`

Also using [+ Add Group] with an AND and `RestLog.QueryString.Any` as token you could filter by:
* Key (constant) 
* Value (`[CurrentEntity].Id`).

 Maybe this improves performance.

**Comment by ce-kkoziel** [comment]
@olmobrutall i was trying like you said.

I have currently concrete entity type selected and filter like this, but still not working.

![obraz](https://user-images.githubusercontent.com/97600039/186666234-330b0292-aea2-43ed-a6b8-da39b570ca52.png)

Client app in default filters do not sends ID rather than this expression.

![obraz](https://user-images.githubusercontent.com/97600039/186666531-76f2c7f0-2d21-4a6a-8b7a-bbb5c48afdbb.png)

When I change this value to concrete ID through dev tools and resend the request, executeQuery returns result.

**Comment by olmobrutall** [comment]
I can not see in the screenshot if you are in a UserQuery or in a SearchControl

If in a UserQuery it should work. 

The code that does the magic is this one: 

https://github.com/signumsoftware/framework/blob/004aa1dd50fc8ab161fe634d2be5fc196a165275/Signum.Entities.Extensions/UserAssets/FilterValueConverters/CurrentEntityConverter.cs#L40

**Comment by ce-kkoziel** [comment]
@olmobrutall  thanks for pointing place in code. We will try to find why it does not work for us.

**Comment by ce-kkoziel** [comment]
@olmobrutall  The expression is not working when the left operand is a string type value. Then expression "[CurrentEntity].Id" is treated just as a string. In my case the Value property from QueryString is a string.

**Comment by olmobrutall** [comment]
in your Starter.cs try adding the following: 

`FilterValueConverter.SpecificConverters.Add(FilterType.String, new CurrentEntityConverter())`

**Comment by ce-kkoziel** [comment]
Converter is executing for string left operand, but actually [CurrentEntity].Id is PrimaryKey type, and type convertion does not work for string <-> PrimaryKey pair, becouse type converter for PrimaryKey type allow convertion only for int, long, guid.

Unable to convert '2faeeb27-b96b-4588-be67-891776382851' (of type PrimaryKey) to type string

I was trying to use [CurrentEntity].Id.ToString expression but .NET throws AmbiguousMatchException. PrimaryKey have 2 ToString method overloads.

Further, I was trying to use [CurrentEntity].Id.Object.ToString but, PrimaryKey Object is a field.

Finally, I was trying to implement custom IFilterValueConverter implementation based on CurrentEntityConverter and use custom implementation of SimpleMemberEvaluator where evaluator will also check fields, but CurrentEntityConverter  have usage of private static currentEntityVariable.

@olmobrutall any other hint how to use it without Framework changes?

**Comment by olmobrutall** [comment]
Hi @ce-kkoziel, to me looks like this line is not doing its work: 

https://github.com/signumsoftware/framework/blob/9f7ad587eae697e4f3e28c09a658bb93b7fc4be2/Signum.Entities.Extensions/UserAssets/FilterValueConverter.cs#L164

The FilterValueConverter already has a `targetType` and the fact that a `PrimaryKey` can not be converted __**to**__ a string is a bug/missing feature. 

Feel free to extend the implementation of `CanConvertTo` / `ConvertTo` in `PrimaryKeyTypeConverter` calling `ToString`.

Changing `ConvertFrom` / `CanConvertFrom` could be more problematic because you don't have context to know that is the expected value (int, long, Guid) 

You don't need to avoid changing the framework at all costs, you can make any reasonable change or create an extension point  for the unreasonable ones.

**Comment by olmobrutall** [comment]
I think this error should not exist since 0cec7f7992602ead8db4a3c663389765cc534390 because now the FilterConverters are registered in a flat list instead of per `FilterType`. 

Closing the issue.
