### ISSUE TITLE
Search controller default queries

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#58]
Hellow Signum community,
I need to create queries that will appear on the search controller of an entity on page load, how can I create such default queries? Is it possible to have more then one default query?

**Comment by olmobrutall** [comment]
> I need to create queries that will appear on the search controller of an entity on page load, how can I create such default queries? 

Signum Framework contains two concepts: 

* DynamicQuery: Written programaticaly in the Logic classes, let you define how the default query looks like. Example: `typeof(User)` or `UserQueries.ActiveUsers`
* User queries: Configurable by the end user, let you save views for later use. Example: `"Users in Human Resources"`

Additionally, you can associate User Queries to an entity so you can do right-click on an entity type and see the user query, or even create dashboard  on the top or the button of the entity. Example: `"Purchases of this User"`

I don't know what you mean exactly with default query. And what you mean by Search controller? Page load you mean a popup or normal full screen search control?

> Is it possible to have more then one default query?

You can have many Dynamic Queries for the same entity, and many user queries for each dynamic query.

**Comment by roiez** [comment]
Thank you Olmo
