### ISSUE TITLE
Read Only property of Entity in UI 

### ISSUE THREAD

**Issue by ce-kkoziel** [signumsoftware/framework#599]
Dear @olmobrutall 

Is there any possibility to configure some property on entity to be read only on UI?

In my example I have CompanyEntity, and I would like to have Name property as readonly on UI.
```csharp
[EntityKind(EntityKind.Main, EntityData.Transactional), PrimaryKey(typeof(Guid))]
public class CompanyEntity : Entity
{
    public string? Name { get; set; }
}
````

**Comment by olmobrutall** [comment]
Depends why you want to make it read-only there are different solutions: 

* Make `public string? Name { get; private set; }`. Readonly for everyone, server-side security. 
* Override `IsPropertyReadonly` Readonly for everyone, server-side security. 
* Make a `<ValueLine ctx={ctx.subCtx(a=>a.name} readOnly/>` if UI security is enought.
* Use the configuration of a Role / AuthRules.tsx , no code changes needed.

**Comment by ce-kkoziel** [comment]
@olmobrutall thanks a lot for explanation. First method works correctly and fits to my needs.
