### ISSUE TITLE
CodeGeneration

### ISSUE THREAD

**Issue by otamimi** [signumsoftware/framework#60]
in Signum.Engine.CodeGeneration.EntityCodeGenertor in method WriteField(string fileName, DiffTable table, DiffColumn col)

at the end of the method it appends the result of string.Format . this will throw an exception as you need to escape the "{" "}"

current: 
    sb.AppendLine("public {0} {1} { get; {2}set; }".FormatWith(type, fieldName.FirstUpper(), IsReadonly(table, col) ? "private" : null));

Should be: 
    sb.AppendLine("public {0} {1} **{**{ get; {2}set; }**}**".FormatWith(type, fieldName.FirstUpper(), IsReadonly(table, col) ? "private" : null));

**Comment by olmobrutall** [comment]
Thanks! I changed it optimistically after C# 5 and I haven't run it since then. 

I assume that you can't create a pull request easily so I'll change it myself.
