### ISSUE TITLE
Problems with getOperationInfo and tryGetOperationInfo

### ISSUE THREAD

**Issue by goldenauge** [signumsoftware/framework#607]
I have problems in several files as example "TypeHelpPage.tsx" to find the method tryGetOperationInfo and getOperationInfo:

if (!Operations.tryGetOperationInfo(TypeHelpOperation.Save, TypeHelpEntity))
    return null;

Operations.getOperationInfo(TypeHelpOperation.Save, TypeHelpEntity).niceName

to solve this problem i changed the code in this way:

if (!tryGetOperationInfo(TypeHelpOperation.Save, TypeHelpEntity))
    return null;

getOperationInfo(TypeHelpOperation.Save, TypeHelpEntity).niceName

and added this import:

import { tryGetOperationInfo, getOperationInfo } from '@framework/Reflection';

do someone else has this problem too?

**Comment by olmobrutall** [comment]
Your solution looks good, can you make a PR? I’m currently in holidays
