### ISSUE TITLE
error starting Load project

### ISSUE THREAD

**Issue by otamimi** [signumsoftware/framework#61]
hi, i couldn't find a better place to ask about this. 

i have been trying to get this framework to work for 2 weeks. i keep getting error after error.

now this:

```C#
InvalidOperationException: EntityKind - OperationLogic inconsistencies:
        RoleEntity is Shared but is NOT 'save protected'
        UserEntity is Main but is NOT 'save protected'
Note: An entity type becomes 'save protected' when a Save operation is defined for it
       at Signum.Engine.Operations.OperationLogic.OperationLogic_Initializing() in E:\lab\cheque\signumFW\ChiqCheque_minimal\Framework\Signum.Engine\Operations\OperationLogic.cs:line 176
       at Signum.Engine.Maps.Schema.OnSchemaCompleted() in E:\lab\cheque\signumFW\ChiqCheque_minimal\Framework\Signum.Engine\Schema\Schema.cs:line 395
       at ChiqCheque_minimal.Logic.Starter.Start(String connectionString) in E:\lab\cheque\signumFW\ChiqCheque_minimal\ChiqCheque_minimal.Logic\Starter.cs:line 87
       at ChiqCheque_minimal.Load.Program.Main(String[] args) in E:\lab\cheque\signumFW\ChiqCheque_minimal\ChiqCheque_minimal.Load\Program.cs:line 43
```

**Comment by mnumeijer** [comment]
In the entity register a Save operation:

    public static class YourEntityNameOperation
    {
        public static ExecuteSymbol<YourEntityName> Save;
    }

In the logic module you need to register:

                new Graph<YourEntityName>.Execute(YourEntityNameOperation.Save)
                {
                    AllowsNew = true,
                    Lite = false,
                    Execute = (e, _) => { },
                }.Register();

**Comment by otamimi** [comment]
great, RoleEntity error is gone, but for the UserEntity a new error
```
 UserEntity is Main but is NOT 'save protected'
```

**Comment by olmobrutall** [comment]
Thanks marcel! 

He is right, you missing defining the save method for this entities, but this is not something that you have to do yourself, just call AuthLogic.Start in the Statt method. 

https://github.com/signumsoftware/southwind/blob/master/Southwind.Logic/Starter.cs


The other possibility is that you want to make a super simple app without authorization. In this case you have to override the foreign keys to User (for example in OperationLog) and connect them to your own  custom user or just connect them to noting. Look for `OverrideAttributes`

**Comment by ghockx1p** [comment]
Hi Olmo,

Can you please elaborate on not needing to define the Save method? I think you cannot simply leave it out. I just commented out the Save method for ApplicationConfigurationEntity and got this message on startup:
`EntityKind - OperationLogic inconsistencies:
   ApplicationConfigurationEntity is Main but is NOT 'save protected'
   Note: An entity type becomes 'save protected' when a Save operation is defined for it`

PS: I am calling AuthLogic.Start(sb, dqm, "System", null); in the Logic.Starter.

**Comment by olmobrutall** [comment]
In general you are right: for Main and Shared entities you have to define a Save method. 

But if you see his exception, is in some well known entities: 

```RoleEntity is Shared but is NOT 'save protected'
        UserEntity is Main but is NOT 'save protected'```

This entities are developed in Signum.Entities.Extensions and the Save method is already defined in AuthLogic. But this method was never called. 

This had happened, probably, because some entity has a pointer to UserEntity and is including the table in the database. For example OperationLog, UserQuery, Etc...
