### ISSUE TITLE
Problems in Entitytables and entitybase

### ISSUE THREAD

**Issue by goldenauge** [signumsoftware/framework#629]
Hi,

i got some problems after updating the last signum framework version:

1- TSSettings was not found
2- NoInfer was not found
3- change boolea to boolean in refletion.ts

![1](https://github.com/signumsoftware/framework/assets/13727800/326306cc-f9c1-4fd0-a38c-9d28d37828a5)
![2](https://github.com/signumsoftware/framework/assets/13727800/945ef291-bff0-44ec-b5e7-e3524f2cd9d1)

**Comment by goldenauge** [comment]
2 is still not working for me here is my tsconfig:
{
  "compilerOptions": {
    "target": "ES2017",
    "sourceMap": false,
    "module": "esnext",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "jsx": "react",
    "incremental": true,
    "outDir": "./ts_out",
    "skipLibCheck": true,
    "composite": true,
    //"noEmit": true,
    "strict": true,
    "declarationMap": true,
    "paths": {
      "@framework/*": [ "../Framework/Signum/React/*" ],
      "@extensions/*": [ "../Framework/Extensions/*" ]
    },
    "lib": [
      "ES2020",
      "dom"
    ]
  },
  "references": [
    { "path": "../Framework/Signum" },
    { "path": "../Framework/Extensions/Signum.Alerts" },
    { "path": "../Framework/Extensions/Signum.Authorization.ActiveDirectory" },
    { "path": "../Framework/Extensions/Signum.Authorization.ResetPassword" },
    { "path": "../Framework/Extensions/Signum.Authorization" },
    { "path": "../Framework/Extensions/Signum.Caching" },
    { "path": "../Framework/Extensions/Signum.Chart" },
    { "path": "../Framework/Extensions/Signum.CodeMirror" },
    { "path": "../Framework/Extensions/Signum.ConcurrentUser" },
    { "path": "../Framework/Extensions/Signum.Dashboard" },
    { "path": "../Framework/Extensions/Signum.DiffLog" },
    { "path": "../Framework/Extensions/Signum.Eval" },
    { "path": "../Framework/Extensions/Signum.Excel" },
    { "path": "../Framework/Extensions/Signum.Files" },
    { "path": "../Framework/Extensions/Signum.Help" },
    { "path": "../Framework/Extensions/Signum.HtmlEditor" },
    { "path": "../Framework/Extensions/Signum.Isolation" },
    { "path": "../Framework/Extensions/Signum.Mailing.MicrosoftGraph" },
    { "path": "../Framework/Extensions/Signum.Mailing" },
    { "path": "../Framework/Extensions/Signum.Map" },
    { "path": "../Framework/Extensions/Signum.Migrations" },
    { "path": "../Framework/Extensions/Signum.Omnibox" },
    { "path": "../Framework/Extensions/Signum.Processes" },
    { "path": "../Framework/Extensions/Signum.Profiler" },
    { "path": "../Framework/Extensions/Signum.Rest" },
    { "path": "../Framework/Extensions/Signum.Scheduler" },
    { "path": "../Framework/Extensions/Signum.SMS" },
    { "path": "../Framework/Extensions/Signum.Templating" },
    { "path": "../Framework/Extensions/Signum.TimeMachine" },
    { "path": "../Framework/Extensions/Signum.Toolbar" },
    { "path": "../Framework/Extensions/Signum.Translation" },
    { "path": "../Framework/Extensions/Signum.UserAssets" },
    { "path": "../Framework/Extensions/Signum.UserQueries" },
    { "path": "../Framework/Extensions/Signum.ViewLog" },
    { "path": "../Framework/Extensions/Signum.Word" }
  ]
}

**Comment by olmobrutall** [comment]
Not about tsconfig but the nuget/npm packages. If you run the upgrade you should get something like this https://github.com/signumsoftware/southwind/commit/322867467efcd7c0e316717aa5844df3cdb2395d
