### ISSUE TITLE
Fetching related information from other tables in the view

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#63]
Hi,
In the view, When I am in a certain entity, I want to fetch data from other tables/entities and arrange the view differently.
I don't need any pre-defined control such as search control for that, I want to handle it manually.

But, I dont want to fetch the data in the razor, it is ugly and I am afraid it will get bigger, Can I take the code to a more suitable place such as controller action? or an interception?

Thanks
Avi

**Comment by olmobrutall** [comment]
Assuming you don't want to rewrite the controller, and you want to use a normal frame with buttons etc...

Just make a static method in a Client that takes your entity and returns all the other related information and call it from razor. 

Von meinem iPhone gesendet
