### ISSUE TITLE
Default search

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#64]

**Comment by mapacheL** [comment]
Hi roiez. 

If for default search you mean the generic search control that is displayed for an entity or query from the omnibox, then I'm afraid there's no way to set default filters, instead you can set the conditions when you register the dqm: http://www.signumsoftware.com/Documentation/framework/master/Signum.Engine/DynamicQuery/DynamicQueries.md

Beside, you can set default filters in search controls using filter options: http://www.signumsoftware.com/Documentation/framework/master/Signum.Windows/DynamicQuery/SearchControl.md

**Comment by roiez** [comment]
Hi Luis, this is exactly the issue, we will overcome it by creating user
queries to support this functionality. Thank you. I closed the issue.



*From:* Luis Delgado [mailto:notifications@github.com]
*Sent:* Wednesday, February 17, 2016 1:20 PM
*To:* signumsoftware/framework
*Cc:* roiez
*Subject:* Re: [framework] Default search (#64)



Hi roiez.

If for default search you mean the generic search control that is displayed
for an entity or query from the omnibox, then I'm afraid there's no way to
set default filters, instead you can set the conditions when you register
the dqm:
http://www.signumsoftware.com/Documentation/framework/master/Signum.Engine/DynamicQuery/DynamicQueries.md

Beside, you can set default filters in search controls using filter
options:
http://www.signumsoftware.com/Documentation/framework/master/Signum.Windows/DynamicQuery/SearchControl.md

—
Reply to this email directly or view it on GitHub
<https://github.com/signumsoftware/framework/issues/64#issuecomment-185159466>
.[image: Image removed by sender.]
