### ISSUE TITLE
None default query and menu name

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#65]
Hi Olmo and the community,
I have two search queries on my Account entity. One with where clause and one without. 
<pre>1.  dqm.RegisterQuery(AccountsQuery.AccountsNoTests, () =>
                                         from e in Database.Query<AccountEntity>()
                                         where e.IsTest == false || e.IsTest == null
2. dqm.RegisterQuery(typeof(AccountEntity), () => from e in Database.Query<AccountEntity>()
</pre>
My menu contains the following node, to call a query limited by the where clause.
<pre>@Html.WebMenu(new WebMenuItem { Link = new FindOptions(AccountsQuery.AccountsNoTests)
   {
              SearchOnLoad = true
   }})
</pre>

I need the menu to show the name Accounts instead of Accounts no tests.
At the same time I am required to keep the query without the where clause accessible from the omnibox.

**Comment by mapacheL** [comment]
Hi roiez.

I think you can achieve the "UI" name setting an attribute with Description in your query enum, something like that:

Public enum AccountsQuery
{
Item1,
Item2,
ItemN,
[Description("Accounts")]
AccountsNotests
}

About the omnibox, I think that all the user queries registered are available in the omnibox by default, just typing enough to reach it among the others entities and queries.


Enviado desde mi iPhone

**Comment by roiez** [comment]
Thank you Enviado

**Comment by olmobrutall** [comment]
Hi roiez,

Instead ir adding description attribute, override the WebMenuItem label using the `Title` property. 

then you'll change the title in the menu without creating ambiguities for the Omnibox.

**Comment by roiez** [comment]
Thank you Olmo
