### ISSUE TITLE
Send email

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#66]
Hi Olmo and the community,
I have created an email template, and now I would like to send an email message.
I am interested in two ways of sending an email:
1.       Send by button click 
2.       Send mail automatically 
Thank you

**Comment by olmobrutall** [comment]
You can create an EmailMessage from a EmailTemplate but you'll need to hard-code it's name in code. Alternatively you can register a SystemEmail and associate the EmailTemplate with this SystemEmail. 

You can use `ResetPasswordRequestMail` as an example.

If by automatically you mean at periodical interervals, then create and send the EmailMessages using an ScheduleTask.

**Comment by roiez** [comment]
Hi Olmo, by automatically I mean sent would be triggered by an event in the code

**Comment by olmobrutall** [comment]
Then the ResetPasswordRequestEmail should be a good example of how to trigger it from your code but still be able to modify the template or change it for another one without doing a deployment

**Comment by roiez** [comment]
OK, I'll use ResetPasswordRequestEmail as an example, thank you
