### ISSUE TITLE
email configuration

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#70]
Hi Olmo,
I need to create a “new email button” on an “account entity” details view, where an e mail 
template will be selected from a dropdown. 
![image](https://cloud.githubusercontent.com/assets/13131520/13812476/177f8f22-eb85-11e5-9490-0bee99e68c53.png)
Clicking on envelope button will open the “new email message” dialog, where the template should be loaded along with the account details rendered in the relevant fields, e.g. addressed to = accounts email etc..
![image](https://cloud.githubusercontent.com/assets/13131520/13812480/1c520070-eb85-11e5-802a-2e9f920209c5.png)
P.S. What I have managed to accomplish so far, is doing all of this programmatically, without opening the "new email message" dialog for the user.

**Comment by olmobrutall** [comment]
Try to take a look at Navigator.ts view methods and all the examples in typescript that you find in extensions. If nothing helps we can meet on Sunday.

**Comment by roiez** [comment]
O'right! Thanx Olmo.
