### ISSUE TITLE
Type Signum.Entities.Authorization.ResetPasswordRequestEntity not found

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#73]
Hi, 
I have generated a new app without "Auth (Reset password)"  and I got this error trying to run the app:

An exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in Signum.Utilities.dll but was not handled in user code

Additional information: Type Signum.Entities.Authorization.ResetPasswordRequestEntity not found in the schema

Any idea why?

**Comment by olmobrutall** [comment]
hi avi. 

Please send the stacktrace

**Comment by avifatal** [comment]
[KeyNotFoundException: Type Signum.Entities.Authorization.ResetPasswordRequestEntity not found in the schema]
   Signum.Utilities.DictionaryExtensions.GetOrThrow(IDictionary`2 dictionary, K key, String messageWithFormat) in C:\Users\avi\Documents\Visual Studio 2015\Projects\risqbo\Framework\Signum.Utilities\Extensions\DictionaryExtensions.cs:100
   Signum.Engine.Basics.TypeLogic.GetCleanName(Type type) in C:\Users\avi\Documents\Visual Studio 2015\Projects\risqbo\Framework\Signum.Engine\Basics\TypesLogic.cs:177
   Signum.Web.EntitySettings`1.get_WebTypeName() in C:\Users\avi\Documents\Visual Studio 2015\Projects\risqbo\Framework\Signum.Web\Facades\EntitySettings.cs:48
   Signum.Web.NavigationManager.Initialize() in C:\Users\avi\Documents\Visual Studio 2015\Projects\risqbo\Framework\Signum.Web\Facades\Navigator.cs:419
   Signum.Web.Navigator.Initialize() in C:\Users\avi\Documents\Visual Studio 2015\Projects\risqbo\Framework\Signum.Web\Facades\Navigator.cs:353
   RisqBo.Web.MvcApplication.WebStart() in C:\Users\avi\Documents\Visual Studio 2015\Projects\risqbo\RisqBo.Web\Global.asax.cs:165
   RisqBo.Web.MvcApplication.Application_Start() in C:\Users\avi\Documents\Visual Studio 2015\Projects\risqbo\RisqBo.Web\Global.asax.cs:104

[HttpException (0x80004005): Type Signum.Entities.Authorization.ResetPasswordRequestEntity not found in the schema]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +9966013
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +352
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): Type Signum.Entities.Authorization.ResetPasswordRequestEntity not found in the schema]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9947380
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

**Comment by olmobrutall** [comment]
The problem resides in your Global.asax.

AuthClient.Start has resetPassword parameter set to true. 

The Create New Application functionality doesn't do this because if has no ability to replace lines or line sub-strings, only to remove lines or files. 

Hope it helps

**Comment by avifatal** [comment]
Yes, it worked, thanks.
You might want to change the code generation when someone not choosing "Auth (Reset password)" to false in global asax...
thanks
