### ISSUE TITLE
Entity Discrimination in razor

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#74]
Hi,
I have 3 Entities.
Customer
CustomerContactPerson (has one Customer)
CustomerCall  (has one Customer, has one CustomerContactPerson)

Each customer may have few contact persons. (standard B2B)

In razor, when I want to fill new CustomerCall, I want to mention which CustomerContactPerson was in the call.
Placing a combo will bring all CustomerContactPersons (from all customers), but I want to show only the related contacts from the related customer.
Is it possible? if not, whats the best workaround?

Thanks

**Comment by olmobrutall** [comment]
EntityCompo has a Data property that is accessible using the sendin parameter of Html.EntityCombo. The you can set a `List<Lite<Entity>>` of the CustomerContactPerson for the Customer of this CustomerCall. 

```
@Html.EntityCombo(cc, c=>c.Contact, ec => ec.Data = cc.Value.Customer.Contacts())
```

Hopefully by the time the razor view is rendered the Customer is already known (maybe using a ConstructFrom?) and you can avoid Ajax complications.
