### ISSUE TITLE
Left join with the framework

### ISSUE THREAD

**Issue by mhamiache** [signumsoftware/framework#75]
How can i do a query with a left join?

Example:
Select *
From account A
Left join Bonus B on A.ID = B.accountID
WHERE B.ID IS NULL

**Comment by ghockx1p** [comment]
This more of a general linq question. Please have a look at [101 LINQ Samples in C#](https://code.msdn.microsoft.com/101-LINQ-Samples-3fb9811b). 
Below is an example of how this should work with the framework:. 

from a in Database.Query<AccountEntity>()
join b in Database.Query<BonusEntity>().DefaultIfEmpty() on a.Id equals b.Account.Id into Bonusses
select new
{
   Entity = s,
   Account.Name,
   no = Bonusses.Sum()
}

**Comment by olmobrutall** [comment]
This link also explains the difference between LINQ outer join and the way Signum Engine does it, more similar to SQL

http://www.signumsoftware.com/Documentation/framework/master/Signum.Engine/Linq/Linq.Join.md
