### ISSUE TITLE
React Searchcontrol Pagination

### ISSUE THREAD

**Issue by ze-german** [signumsoftware/framework#77]
If you navigate to page 3 of searchresults and then add a filter returning a single result you get "no results found" and trying to display results 41-40 of 1.

Navigating to page 1 solves the issue.

**Comment by olmobrutall** [comment]
After changing the Filters you press Search.

If you press Search without changing the filters you expect Page = 1 or Page = CurrentPage?

**Comment by olmobrutall** [comment]
Its fixed in React :)
