### ISSUE TITLE
Why doesn't ChildCollectionChanged event fire?

### ISSUE THREAD

**Issue by ghockx1p** [signumsoftware/framework#83]
I have a failing unit test because the ChildCollectionChanged event in my entity doesn't fire. I have created a similar situation in Southwind.Load where it also doesn't fire. Can anyone explain why it doesn't fire?
`
        // This is the declaration of the Mlist in OrderEntity
        [NotNullable, ValidateChildProperty, NotifyChildProperty, NotifyCollectionChanged]
        [NoRepeatValidator]
        public MList<OrderDetailsEntity> Details { get; set; } = new MList<OrderDetailsEntity>();

        // Just copy-paste following line into Southwind.Load
        private static void TestChildCollectionChanged()
        {
            Schema.Current.Initialize();

            UserEntity employee;

            using (AuthLogic.Disable())
            {
                employee = Database.RetrieveAll<UserEntity>().FirstOrDefault(u => u.UserName == "Steven");
            }

            using (UserHolder.UserSession(employee))
            {
                var jonas = Database.Query<PersonEntity>().SingleEx(p => p.FirstName == "Jonas");

                var order = jonas.ConstructFrom(OrderOperation.CreateOrderFromCustomer);

                var konbu = Database.Query<ProductEntity>().SingleEx(p => p.ProductName.Contains("Konbu"));

                var line = new OrderDetailsEntity
                {
                    Product = konbu.ToLite(),
                    UnitPrice = konbu.UnitPrice,
                    Quantity = 1,
                    Discount = 0,
                };

                // The next line should fire the event
                order.Details.Add(line);

                order.Execute(OrderOperation.SaveNew);
            }
        }
`

**Comment by olmobrutall** [comment]
Try calling base.RebindEvents() in the constructor or your particular entity and/or OrderEntity. I think this is the problem. 

I can not add the method in ModifiableEntity constructor because this is Calle before your fields are initialized.

**Comment by ghockx1p** [comment]
Thanks for the quick reply Olmo! Your suggestion was spot on. The event is getting fired again.
